target("psnr")
    set_kind("binary")
    add_files("src/main_psnr.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")

target("histogram")
    set_kind("binary")
    add_files("src/main_histogram.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")

target("permut")
    set_kind("binary")
    add_files("src/main_permut.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")

target("rpermut")
    set_kind("binary")
    add_files("src/main_rpermut.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")

target("encrypt")
    set_kind("binary")
    add_files("src/main_encrypt.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")

target("decrypt")
    set_kind("binary")
    add_files("src/main_decrypt.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")

target("decrypt_bf")
    set_kind("binary")
    add_files("src/main_decrypt_bf.cpp")
    add_files("src/libs/*.cpp")
    add_includedirs("include")